### ISSUE TITLE
Clarification re applicable entities?

### ISSUE THREAD

**Issue by mark-cohen** [DanaEpp/MSP-Vendors-VDP-BBP#1]
@DanaEpp - is the intent of this repo to also include 3rd parties in the MSP ecosystem, ie: an EDR vendor that while not offering an MSP product directly per say, does offer an integration with an MSP product - or limit the scope exclusively to MSP vendors themselves?

**Comment by DanaEpp** [comment]
Great question @mark-cohen. 

In my mind, any vendor that builds software that is consumed or sold by IT Service Providers (including MSPs) in which vulnerabilities in their software could be weaponized to allow attack should be considered.  I'd rather have a wider, more vague scope than limit it to a subset that may end up showing gaps.

As an example, MSPs routinely drop applications on their customer's networks and endpoints. Those applications are ripe for the picking, especially for things like 3rd party dependency attacks. That's pretty clear. Yet sometimes the MSP itself consumes a cloud service to manage services (like telephony or VoIP for instance) in which an attack of the web portal of the VoIP provider may be a pivot point into the end customer's own infrastructure.  

Both should be considered. 

This list COULD get very long over time. And I am OK with that. It becomes a perfect index to allow security researchers to decide what products interest them, and what sort of vulnerability analysis they want to perform. 

I am also tracking this over time to see if this industry actually improves. So few have VDPs, never mind BBP. Will that change over time as vendors see the value of security researchers? Guess we will find out.

Does that answer your original question? Do you have vendors you would like to see included?

**Comment by mark-cohen** [comment]
It does and I do. The list will likely grow long indeed, but thats an indirect value-add re fleshing out the MSP ecosystem, increasing the transparency re who's running which apps and tracking the changes to these relationships.
