### ISSUE TITLE
CW has a BB Program

### ISSUE THREAD

**Issue by jmslagle** [DanaEpp/MSP-Vendors-VDP-BBP#3]
It's invite only at present but it exists - I'm in it/

**Comment by DanaEpp** [comment]
As per the research notes:

> Any bug bounty programs that are currently private, even if I know of them, will still be marked as "No". Any vendor that wishes to update that to a Yes simply has to provide me with a link to a landing page which offers security researchers a way to apply to the private program.

As CW is invite only, security researchers have no way of knowing how to participate in the BBP. Any vendor that publicly provides instructions on how to get on an invite only/private BBP will have that column marked as "yes" with a link to that invitation / instruction page. That doesn't mean a vendor has to accept a security researcher; but it shouldn't be hidden away. 

Being open and transparent is one of the whole reasons for this repo.

Do you feel that is a reasonable stance?

**Comment by DanaEpp** [comment]
Closing issue as answered.
